name: Postgres Client + Python

on:
  push:

jobs:
  test:
    name: Postgres Client + Python
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports: 
          - 5432/tcp
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install PostgreSQL 12 client required for loading structure.sql
        run: |
          sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
          wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install libpq-dev postgresql-12 postgresql-client-12
      - name: Check installed components for PostgreSQL
        env:
          # use localhost for the host here because we are running the job on the VM.
          # If we were running the job on in a container this would be postgres
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        run: |
          pg_isready
          cd sql/
          export POSTGRES_PASSWORD="postgres"
          psql --host=localhost --dbname=postgres --username=postgres
          psql -U postgres -d postgres < sample-table.sql